const JOB_STAGES_ENUM = {
  PROSPECT: "PROSPECT",
  INTERVIEWING: "INTERVIEWING",
  OFFER: "OFFER",
  REJECTED: "REJECTED",
  ACCEPTED: "ACCEPTED"
};

const FORECAST_PROBABILITY_PERCENTAGE = {
  PROSPECT: 10,
  INTERVIEWING: 25,
  OFFER: 75,
  REJECTED: 0,
  ACCEPTED: 100
};
const PER_JOB_AMOUNT = 1000;
module.exports = {
  JOB_STAGES_ENUM,
  PER_JOB_AMOUNT,
  FORECAST_PROBABILITY_PERCENTAGE
};
